Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
   config.vm.network "forwarded_port", guest: 3000, host: 3000
   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y curl
     curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
     sudo apt-get install -y nodejs
     sudo npm install -g nodemon
   SHELL
end
