apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-pedidos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sistema-pedidos
  template:
    metadata:
      labels:
        app: sistema-pedidos
    spec:
      containers:
        - name: sistema-pedidos
          image: sistema-pedidos:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/sistema-pedidos"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}